POST http://localhost:3000/api/location/add_new
auth-token: {{AUTH_TOKEN}}
content-type: application/json

{
    "public": true,
    "owner": "5ea4847de4886b20a469df42",
    "name": "keller kneipe",
    "street": "Hauptstraße 1",
    "zip": "12345",
    "city": "Mannheim",
    "country": "GER",
    "lon": 49.492267,
    "lat": 8.472750
}