GET http://localhost:3000/api/content/bierdeckel
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWE0ODQ3ZGU0ODg2YjIwYTQ2OWRmNDIiLCJpYXQiOjE1ODc4NDAyMjF9.CQR64xIYbdIleXT0csjigl4bNjeEER0WqYH8Bytrjms