POST http://localhost:3000/api/user/edit_user
auth-token: {{AUTH_TOKEN}}
content-type: application/json

{
    "auth-token": "{{AUTH_TOKEN}}",
    "edited_user_id": "{{ELLIOT_ID}}",
    "new_name": "eliot",
    "new_email": "new_mail@test.com"
}

